version: '2'

services:
  http-server:
    image: nginx:1.11
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ./docker-compose/log:/var/log
      - ./docker-compose/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - source-listener
    networks:
      - code-network

  source-listener:
    build: ../
    volumes:
      - ../:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PAGINATION_LIMIT: 200
    links:
      - redis
    networks:
      - code-network

  redis:
    image: redis:3.0.7
    ports:
      - "6379:6379"
    networks:
      - code-network

  test:
    build: ./
    volumes:
      - ../:/app
    environment:
      DOMAIN: http-server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PAGINATION_LIMIT: 200
    links:
      - redis
      - http-server
    networks:
      - code-network
    command: "/app/vendor/bin/phpunit /app/docker_tests/scenarios/"

networks:
    code-network:
        driver: bridge
